### ISSUE TITLE
Village loading crash

### ISSUE THREAD

**Issue by atpoe** [MarkusBordihn/BOs-My-Personal-Apartment#3]
crashes when trying to load any village, with or without mods

[crash-2023-08-30_02.36.39-server.txt](https://github.com/MarkusBordihn/BOs-My-Personal-Apartment/files/12470926/crash-2023-08-30_02.36.39-server.txt)

**Comment by MarkusBordihn** [comment]
Thanks for the report. The issue should be fixed now. 
It could be that you need to regenerate the world so that the corrected structure files are used.
